List wordList = [
  {
    "morpheme": "通常",
    "surface": "天気",
    "with_whitespace": false,
    "pos": "名詞",
    "pos_detail1": "一般",
    "pos_detail2": "",
    "pos_detail3": "",
    "conjugated_type": "",
    "conjugated_form": "",
    "baseform": "天気",
    "reading": "テンキ",
    "pronunciation": "テンキ",
    "word_cost": 4448,
    "c_cost": -283,
    "cost": 4165,
    "ime_romaji": "tennki"
  },
  {
    "morpheme": "通常",
    "surface": "が",
    "with_whitespace": false,
    "pos": "助詞",
    "pos_detail1": "格助詞",
    "pos_detail2": "一般",
    "pos_detail3": "",
    "conjugated_type": "",
    "conjugated_form": "",
    "baseform": "が",
    "reading": "ガ",
    "pronunciation": "ガ",
    "word_cost": 3866,
    "c_cost": -4721,
    "cost": -855,
    "ime_romaji": "ga"
  },
  {
    "morpheme": "通常",
    "surface": "いい",
    "with_whitespace": false,
    "pos": "形容詞",
    "pos_detail1": "自立",
    "pos_detail2": "",
    "pos_detail3": "",
    "conjugated_type": "形容詞・イイ",
    "conjugated_form": "基本形",
    "baseform": "いい",
    "reading": "イイ",
    "pronunciation": "イイ",
    "word_cost": 5610,
    "c_cost": -4001,
    "cost": 1609,
    "ime_romaji": "ii"
  },
  {
    "morpheme": "通常",
    "surface": "から",
    "with_whitespace": false,
    "pos": "助詞",
    "pos_detail1": "接続助詞",
    "pos_detail2": "",
    "pos_detail3": "",
    "conjugated_type": "",
    "conjugated_form": "",
    "baseform": "から",
    "reading": "カラ",
    "pronunciation": "カラ",
    "word_cost": 5649,
    "c_cost": -4465,
    "cost": 1184,
    "ime_romaji": "kara"
  },
  {
    "morpheme": "通常",
    "surface": "、",
    "with_whitespace": false,
    "pos": "記号",
    "pos_detail1": "読点",
    "pos_detail2": "",
    "pos_detail3": "",
    "conjugated_type": "",
    "conjugated_form": "",
    "baseform": "、",
    "reading": "、",
    "pronunciation": "、",
    "word_cost": -2435,
    "c_cost": -1673,
    "cost": -4108,
    "ime_romaji": ","
  },
  {
    "morpheme": "通常",
    "surface": "散歩",
    "with_whitespace": false,
    "pos": "名詞",
    "pos_detail1": "サ変接続",
    "pos_detail2": "",
    "pos_detail3": "",
    "conjugated_type": "",
    "conjugated_form": "",
    "baseform": "散歩",
    "reading": "サンポ",
    "pronunciation": "サンポ",
    "word_cost": 4505,
    "c_cost": -358,
    "cost": 4147,
    "ime_romaji": "sannpo"
  },
  {
    "morpheme": "通常",
    "surface": "し",
    "with_whitespace": false,
    "pos": "動詞",
    "pos_detail1": "自立",
    "pos_detail2": "",
    "pos_detail3": "",
    "conjugated_type": "サ変・スル",
    "conjugated_form": "連用形",
    "baseform": "する",
    "reading": "シ",
    "pronunciation": "シ",
    "word_cost": 8718,
    "c_cost": -5350,
    "cost": 3368,
    "ime_romaji": "si"
  },
  {
    "morpheme": "通常",
    "surface": "ましょ",
    "with_whitespace": false,
    "pos": "助動詞",
    "pos_detail1": "",
    "pos_detail2": "",
    "pos_detail3": "",
    "conjugated_type": "特殊・マス",
    "conjugated_form": "未然ウ接続",
    "baseform": "ます",
    "reading": "マショ",
    "pronunciation": "マショ",
    "word_cost": 6049,
    "c_cost": -6122,
    "cost": -73,
    "ime_romaji": "masixyo"
  },
  {
    "morpheme": "通常",
    "surface": "歌い",
    "with_whitespace": false,
    "pos": "動詞",
    "pos_detail1": "自立",
    "pos_detail2": "",
    "pos_detail3": "",
    "conjugated_type": "五段・ワ行促音便",
    "conjugated_form": "連用形",
    "baseform": "歌う",
    "reading": "ウタイ",
    "pronunciation": "ウタイ",
    "word_cost": 7472,
    "c_cost": -7475,
    "cost": -3,
    "ime_romaji": "utai"
  }
];
